/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DatePicker: typeof import('./components/external/DatePicker.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    FormInput: typeof import('./components/FormInput.vue')['default']
    FormResult: typeof import('./components/FormResult.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
